"use client";

import { useRef, useMemo } from "react";
import { useFrame, useLoader } from "@react-three/fiber";
import { SVGLoader } from "three/examples/jsm/loaders/SVGLoader.js";
import * as THREE from "three";

export default function Logo3D({ 
  animationState 
}: { 
  animationState?: { scale: number; opacity: number } 
}) {
  const groupRef = useRef<THREE.Group>(null);

  // Load the SVG logo generated by the Python script
  const svg = useLoader(SVGLoader, "/images/logo.svg");

  // Extract shapes from the SVG paths
  const shapes = useMemo(() => {
    return svg.paths.map((p) => ({
      color: p.color,
      shapes: p.toShapes(true),
    }));
  }, [svg]);

  // Extrude settings for a premium 3D bevel effect
  const extrudeSettings = useMemo(() => ({
    depth: 15,
    bevelEnabled: true,
    bevelThickness: 3,
    bevelSize: 1,
    bevelSegments: 4,
    curveSegments: 16,
  }), []);

  // Scale factor: SVG coordinates are -300 to 300, scale down to fit in Three.js space
  // We flip the Y-axis (-scale) because SVG coordinates go down while Three.js goes up.
  const baseScale = 0.0022;

  // Continuous smooth rotation and gentle levitation/floating effect
  useFrame((state) => {
    if (groupRef.current) {
      const elapsed = state.clock.getElapsedTime();
      
      // Rotate the logo smoothly around Y-axis
      groupRef.current.rotation.y = elapsed * 0.35;
      
      // Floating motion up and down
      groupRef.current.position.y = Math.sin(elapsed * 1.2) * 0.04;
      
      // Subtly rotate on X and Z axis to give a dynamic, alive feel
      groupRef.current.rotation.x = Math.sin(elapsed * 0.6) * 0.08;
      groupRef.current.rotation.z = Math.cos(elapsed * 0.4) * 0.05;

      // Apply dynamic scale and opacity from GSAP scroll trigger
      if (animationState) {
        const s = baseScale * animationState.scale;
        groupRef.current.scale.set(s, -s, s);

        groupRef.current.traverse((child) => {
          if (child instanceof THREE.Mesh) {
            const materials = Array.isArray(child.material) ? child.material : [child.material];
            materials.forEach((mat) => {
              mat.transparent = true;
              mat.opacity = animationState.opacity;
            });
          }
        });
      }
    }
  });

  return (
    <group ref={groupRef} position={[0, 0.05, 0.3]} scale={[baseScale, -baseScale, baseScale]}>
      {shapes.map((path, pathIndex) =>
        path.shapes.map((shape, shapeIndex) => (
          <mesh 
            key={`${pathIndex}-${shapeIndex}`} 
            position={[0, 0, -7.5]} // Center the extrusion along the Z axis (depth / 2)
            castShadow 
            receiveShadow
          >
            <extrudeGeometry args={[shape, extrudeSettings]} />
            <meshPhysicalMaterial
              color="#D4AF37" // Beautiful metallic gold
              metalness={0.95}
              roughness={0.12}
              clearcoat={1.0}
              clearcoatRoughness={0.05}
              reflectivity={1.0}
              side={THREE.DoubleSide}
            />
          </mesh>
        ))
      )}
    </group>
  );
}
